Name:           ros-melodic-ifopt
Version:        2.0.3
Release:        0%{?dist}
Summary:        ROS ifopt package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/ethz-adrl/ifopt
Source0:        %{name}-%{version}.tar.gz

Requires:       coin-or-CoinUtils-devel
Requires:       eigen3-devel
Requires:       ros-melodic-catkin
BuildRequires:  cmake
BuildRequires:  coin-or-CoinUtils-devel
BuildRequires:  eigen3-devel

%description
An Eigen- based interface to Nonlinear Programming solver Ipopt. Inuitive and
efficient C++ implementation of variables, costs and constraints using Eigen.
Easy integration in your projects in catkin or pure cmake.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Jul 10 2018 Alexander W. Winkler <winklera@ethz.ch> - 2.0.3-0
- Autogenerated by Bloom

